image: node:14

stages:
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  YARN_CACHE_FOLDER: "/root/.cache/yarn"

cache:
  paths:
    - /root/.cache/
    - $CI_PROJECT_DIR/node_modules/
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  timeout: 5m
  script:
    # Uncomment for debugging
    # - export
    # - yarn cache dir
    - cd -- "$CI_PROJECT_DIR"
    - yarn --frozen-lockfile
    - yarn test
  coverage: '/Lines\s+:\s(\d+.?\d+)%/'
  artifacts:
    paths:
      - coverage
    reports:
      cobertura: coverage/cobertura-coverage.xml
    expire_in: 2 weeks
